---
abstract: 'A distributed execution platform for Perl'
author:
  - '"Jeff Ober" <"jeffober@gmail.com">'
build_requires:
  List::Util: '0'
  Sub::Override: '0'
  Test::More: '0'
  Test::TinyMocker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Argon
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: '0'
  Const::Fast: '0'
  Coro: '0'
  Coro::PrioChannel: '0.005'
  Coro::ProcessPool: '0.15'
  Data::UUID: '0'
  Guard: '0'
  Log::Log4perl: '0'
  Module::Load: '0'
  Moo: '0'
  MooX::HandlesVia: '0'
  Types::Standard: '0'
version: 0.15_02
