---
abstract: 'A distributed execution platform for Perl'
author:
  - "\"Jeff Ober\" <\"jeffober@gmail.com\">"
build_requires:
  List::Util: 0
  Test::More: 0
  Test::TinyMocker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Argon
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 0
  Const::Fast: 0
  Coro: 0
  Coro::ProcessPool: 0
  Data::UUID: 0
  Guard: 0
  Moo: 0
  MooX::HandlesVia: 0
  Types::Standard: 0
  UNIVERSAL::require: 0
version: 0.10
