---
abstract: 'A robust, distributed services platform.'
author:
  - "\"Jeff Ober\" <\"jeffober@gmail.com\">"
build_requires:
  IO::Capture::Stderr: 0
  Test::More: 0
  Test::Refcount: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Argon
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 0
  Coro: 0
  Coro::PrioChannel: 0.005
  Data::UUID: 0
  Moose: 0
  MooseX::StrictConstructor: 0
  String::Escape: 0
  UNIVERSAL::require: 0
  namespace::autoclean: 0
version: 0.05
